### ISSUE TITLE
Project Part 2 - Preparation (Oct. 18 - 4:00 pm)

### ISSUE THREAD

**Issue by WJXHenry** [CMPUT301F19T22/3OwO1#12]
This is for tracking progress on part 2 of the project. I've just copied the part 2 description from eClass here for better accessibility.

- [x] **Product Backlog**
  - Form the initial partial user stories into a backlog of the product's requirements. For each user story, complete its rationale, its estimated size in story points, and risk level (i.e., low, medium, or high). These requirements will likely evolve and should be maintained up-to-date throughout the project. Make sure they are numbered for easy reference.
- [x] **User Interface Mockups and Storyboard Sequences**
  - Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.
- [x] **Object-Oriented Analysis**
  - Document your initial object-oriented analysis using a UML class diagram (or diagrams), focusing on the most important anticipated classes, interfaces, and relationships. Add notes if the purpose of a class, interface, or relationship is likely not clear to an outsider. The diagram(s) will likely evolve.
- [x] **Glossary and Information Sources**
  - Define any special terminology in the application domain (i.e., not programming terms). Provide a list of useful informational references or links to related or competitive products. Enter this information in your team wiki. Please clearly state the open source license for your project.

_**Notes**_:
- For the product backlog, I think it would be a good idea to use GitHub's project boards. I've created one [here](https://github.com/CMPUT301F19T22/3OwO1/projects/1). Another option could be [Trello](https://trello.com/en).
- Diagrams must be embedded as images in the [wiki](https://github.com/CMPUT301F19T22/3OwO1/wiki).

**Comment by WJXHenry** [comment]
[Here is the **User Interface Mockups and Storyboard Sequences** example showed in class.](https://github.com/CMPUT301F15T05/cuddly-quack/wiki/User-Interface-Mockup-and-Storyboard)
